FROM node:22-alpine AS deps
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.15.2 --activate
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

FROM node:22-alpine AS builder
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@9.15.2 --activate
ENV NEXT_TELEMETRY_DISABLED=1
ARG DATABASE_URL
ARG DATABASE_AUTH_TOKEN
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG EMAIL_SERVER
ARG EMAIL_FROM
ARG TWITTER_API_KEY
ARG TWITTER_API_SECRET
ARG TWITTER_ACCESS_TOKEN
ARG TWITTER_ACCESS_SECRET
ARG TWITTER_CLIENT_ID
ARG TWITTER_CLIENT_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_AUTH_TOKEN=$DATABASE_AUTH_TOKEN
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
ENV EMAIL_SERVER=$EMAIL_SERVER
ENV EMAIL_FROM=$EMAIL_FROM
ENV TWITTER_API_KEY=$TWITTER_API_KEY
ENV TWITTER_API_SECRET=$TWITTER_API_SECRET
ENV TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
ENV TWITTER_ACCESS_SECRET=$TWITTER_ACCESS_SECRET
ENV TWITTER_CLIENT_ID=$TWITTER_CLIENT_ID
ENV TWITTER_CLIENT_SECRET=$TWITTER_CLIENT_SECRET
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

FROM node:22-alpine AS runner
WORKDIR /app
ARG DATABASE_URL
ARG DATABASE_AUTH_TOKEN
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ARG EMAIL_SERVER
ARG EMAIL_FROM
ARG TWITTER_API_KEY
ARG TWITTER_API_SECRET
ARG TWITTER_ACCESS_TOKEN
ARG TWITTER_ACCESS_SECRET
ARG TWITTER_CLIENT_ID
ARG TWITTER_CLIENT_SECRET
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_AUTH_TOKEN=$DATABASE_AUTH_TOKEN
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET
ENV EMAIL_SERVER=$EMAIL_SERVER
ENV EMAIL_FROM=$EMAIL_FROM
ENV TWITTER_API_KEY=$TWITTER_API_KEY
ENV TWITTER_API_SECRET=$TWITTER_API_SECRET
ENV TWITTER_ACCESS_TOKEN=$TWITTER_ACCESS_TOKEN
ENV TWITTER_ACCESS_SECRET=$TWITTER_ACCESS_SECRET
ENV TWITTER_CLIENT_ID=$TWITTER_CLIENT_ID
ENV TWITTER_CLIENT_SECRET=$TWITTER_CLIENT_SECRET
RUN addgroup -S nodejs && adduser -S nextjs -G nodejs
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
USER nextjs
EXPOSE 3000
CMD ["node_modules/.bin/next", "start"]
